import { NextResponse } from "next/server"
import { createServerSupabaseClient } from "@/lib/supabase/server"

export async function GET(request: Request) {
  try {
    const supabase = await createServerSupabaseClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const chatId = searchParams.get("chatId")
    const title = searchParams.get("title") || "Research Report"
    const content = searchParams.get("content") || ""

    if (!chatId) {
      return NextResponse.json({ error: "Missing chatId" }, { status: 400 })
    }

    const { data: messages } = await supabase
      .from("messages")
      .select("role, content")
      .eq("chat_id", chatId)
      .order("created_at", { ascending: true })

    if (!messages) {
      return NextResponse.json({ error: "No messages found" }, { status: 404 })
    }

    const reportContent = content || messages
      .filter((m: any) => m.role === "assistant")
      .map((m: any) => m.content)
      .join("\n\n")

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 40px; line-height: 1.6; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 20px; }
    p { margin-bottom: 16px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div>${reportContent.split("\n").filter(line => line.trim()).map(line => {
    if (line.startsWith("# ")) return `<h1>${line.slice(2)}</h1>`
    if (line.startsWith("## ")) return `<h2>${line.slice(3)}</h2>`
    if (line.startsWith("### ")) return `<h3>${line.slice(4)}</h3>`
    if (line.startsWith("- ")) return `<li>${line.slice(2)}</li>`
    if (line.match(/^\d+\.\s/)) return `<li>${line.replace(/^\d+\.\s/, "")}</li>`
    return `<p>${line}</p>`
  }).join("\n")}</div>
  <div class="footer">
    Generated by MicroManus Deep Research Agent
  </div>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="${title.replace(/[^a-zA-Z0-9]/g, "_")}.html"`,
      },
    })
  } catch (error: any) {
    console.error("PDF error:", error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
